import { useState, useRef } from "react";
import { UploadCloud, ScanSearch, AlertTriangle, CheckCircle2, FileVideo, PlusCircle } from "lucide-react";
import api from "../../services/api.js";

function severityFromProbability(p) {
  if (p >= 80) return "critical";
  if (p >= 55) return "high";
  if (p >= 25) return "medium";
  return "low";
}

export default function AIDetection() {
  const fileInputRef = useRef(null);
  const [fileName, setFileName] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [creating, setCreating] = useState(false);
  const [created, setCreated] = useState(null);
  const [location, setLocation] = useState("Golmuri Road, Jamshedpur");
  const [coords, setCoords] = useState({ latitude: 22.7870, longitude: 86.2085 });

  function onPickFile(e) {
    const file = e.target.files?.[0];
    setResult(null);
    setCreated(null);
    setError(null);
    setFileName(file ? file.name : null);
  }

  async function runDetection() {
    setAnalyzing(true);
    setError(null);
    setCreated(null);
    try {
      const res = await api.post("/detection/analyze", {
        fileName,
        sourceLabel: fileName || "Live demo feed sample",
      });
      setResult(res.data);
    } catch (err) {
      setError(err.message);
    } finally {
      setAnalyzing(false);
    }
  }

  async function createIncidentFromDetection() {
    if (!result) return;
    setCreating(true);
    setError(null);
    try {
      const severity = severityFromProbability(result.analysis.accidentProbability);
      const res = await api.post("/incidents", {
        type: "accident",
        location,
        latitude: coords.latitude,
        longitude: coords.longitude,
        severity,
        source: "ai_camera",
        aiConfidence: result.analysis.accidentProbability,
        description: `Auto-flagged from AI detection upload (${result.sourceLabel}). Vehicles: ${result.analysis.vehicles}, pedestrians: ${result.analysis.pedestrians}, traffic: ${result.analysis.trafficLevel}.`,
      });
      setCreated(res.data.incident);
    } catch (err) {
      setError(err.message);
    } finally {
      setCreating(false);
    }
  }

  const hasAccident = result && result.analysis.accidentProbability >= 55;

  return (
    <div className="p-6 space-y-5 max-w-3xl">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <ScanSearch className="w-5 h-5 text-primary" />
          <h1 className="font-display font-semibold text-xl">AI Incident Detection</h1>
        </div>
        <span className="text-xs font-mono text-warning bg-warning/10 border border-warning/20 rounded-full px-3 py-1">
          DEMO UPLOAD — DETECTION SIMULATED
        </span>
      </div>
      <p className="text-sm text-muted -mt-3">
        Upload a traffic camera clip or photo to run AI accident/hazard detection. In this demo build no real
        computer-vision model runs — results are generated by a simulation layer with the exact response shape a
        real detector would return, so the integration point (<code className="text-xs">ai-service/</code>) can be
        swapped in later without changing this page.
      </p>

      <div className="bg-surface border border-line rounded-xl p-6 space-y-4">
        <button
          onClick={() => fileInputRef.current?.click()}
          className="w-full border-2 border-dashed border-line rounded-xl py-10 flex flex-col items-center gap-2 text-muted hover:border-primary/40 hover:text-ink transition-colors"
        >
          {fileName ? <FileVideo className="w-8 h-8 text-primary" /> : <UploadCloud className="w-8 h-8" />}
          <span className="text-sm">{fileName || "Click to select a demo image or video"}</span>
          <span className="text-xs">MP4, JPG, PNG — not actually uploaded in demo mode</span>
        </button>
        <input ref={fileInputRef} type="file" accept="image/*,video/*" onChange={onPickFile} className="hidden" />

        <button
          onClick={runDetection}
          disabled={analyzing}
          className="w-full bg-primary hover:bg-primary/90 disabled:opacity-50 text-white text-sm font-medium rounded-lg py-2.5 transition-colors flex items-center justify-center gap-2"
        >
          <ScanSearch className="w-4 h-4" />
          {analyzing ? "Running detection…" : "Run AI Detection"}
        </button>
      </div>

      {error && <p className="text-emergency text-sm">{error}</p>}

      {result && (
        <div className="bg-surface border border-line rounded-xl p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="font-display font-semibold">Detection Result</h2>
            <span className="text-xs text-muted">{result.sourceLabel}</span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <Stat label="Vehicles" value={result.analysis.vehicles} />
            <Stat label="Pedestrians" value={result.analysis.pedestrians} />
            <Stat label="Traffic level" value={result.analysis.trafficLevel} />
            <Stat label="Crowd density" value={result.analysis.crowdDensity} />
          </div>

          <div>
            <div className="flex items-center justify-between text-sm mb-1.5">
              <span className="text-muted">Accident probability</span>
              <span className={hasAccident ? "text-emergency font-mono" : "text-success font-mono"}>
                {result.analysis.accidentProbability}%
              </span>
            </div>
            <div className="h-2 rounded-full bg-white/5 overflow-hidden">
              <div
                className={`h-full rounded-full ${hasAccident ? "bg-emergency" : "bg-success"}`}
                style={{ width: `${result.analysis.accidentProbability}%` }}
              />
            </div>
          </div>

          {hasAccident ? (
            <div className="flex items-center gap-2 text-sm text-emergency bg-emergency/10 border border-emergency/20 rounded-lg px-3 py-2.5">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              High probability of an incident — review and create an incident record if warranted.
            </div>
          ) : (
            <div className="flex items-center gap-2 text-sm text-success bg-success/10 border border-success/20 rounded-lg px-3 py-2.5">
              <CheckCircle2 className="w-4 h-4 shrink-0" />
              No significant hazard detected in this feed.
            </div>
          )}

          {hasAccident && !created && (
            <div className="space-y-2 pt-2 border-t border-line">
              <div className="grid sm:grid-cols-2 gap-2">
                <label className="text-xs text-muted space-y-1 block">
                  Location label
                  <input
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    className="w-full bg-base border border-line rounded-lg px-3 py-2 text-sm text-ink"
                  />
                </label>
                <div className="grid grid-cols-2 gap-2">
                  <label className="text-xs text-muted space-y-1 block">
                    Latitude
                    <input
                      type="number"
                      step="0.0001"
                      value={coords.latitude}
                      onChange={(e) => setCoords((c) => ({ ...c, latitude: Number(e.target.value) }))}
                      className="w-full bg-base border border-line rounded-lg px-3 py-2 text-sm text-ink"
                    />
                  </label>
                  <label className="text-xs text-muted space-y-1 block">
                    Longitude
                    <input
                      type="number"
                      step="0.0001"
                      value={coords.longitude}
                      onChange={(e) => setCoords((c) => ({ ...c, longitude: Number(e.target.value) }))}
                      className="w-full bg-base border border-line rounded-lg px-3 py-2 text-sm text-ink"
                    />
                  </label>
                </div>
              </div>
              <button
                onClick={createIncidentFromDetection}
                disabled={creating}
                className="flex items-center gap-2 text-sm bg-emergency hover:bg-emergency/90 disabled:opacity-50 text-white rounded-lg px-4 py-2 transition-colors"
              >
                <PlusCircle className="w-4 h-4" />
                {creating ? "Creating…" : "Create Incident From Detection"}
              </button>
            </div>
          )}

          {created && (
            <div className="flex items-center gap-2 text-sm text-primary bg-primary/10 border border-primary/20 rounded-lg px-3 py-2.5">
              <CheckCircle2 className="w-4 h-4 shrink-0" />
              Incident {created.incidentId} created and sent to Incident Center.
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function Stat({ label, value }) {
  return (
    <div className="bg-base border border-line rounded-lg px-3 py-2.5">
      <p className="text-xs text-muted mb-0.5">{label}</p>
      <p className="text-sm text-ink capitalize font-mono">{value}</p>
    </div>
  );
}
